a=eval(input("Enter the value of a : "))
b=eval(input("Enter the value of b : "))
print("Addition :",a+b)
print("Subtraction : ",a-b)
print("Multiplication :",a*b)
print("Division: ", a/b)
print("Modulus : ", a%b)
print("Exponent : ",a**b)
print("Floor Division : ", a//b)
